Add baseDir to babel plugin to enable caching
tildeio/ember-element-helper pull request #54
Opened 2021-05-20 14:01 UTC by mydea

The build under embroider complained that this plugin prevented proper caching. I've tried it in our app and defining the `baseDir` made the warning go away.

Fixes https://github.com/tildeio/ember-element-helper/issues/53

2021-06-10 13:25 UTC, mydea commented
Any chance to get this merged? Would be nice to get rid of this warning :)

2021-06-11 13:39 UTC, rwjblue approved these changes
Seems good to me! Thank you!

2021-06-11 13:41 UTC, rwjblue requested changes
```$ eslint .

/home/runner/work/ember-element-helper/ember-element-helper/lib/element-helper-syntax-plugin.js
Error:   43:2  error  Unnecessary semicolon  no-extra-semi

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2021-06-14 05:58 UTC, mydea commented
> ```
> 
> /home/runner/work/ember-element-helper/ember-element-helper/lib/element-helper-syntax-plugin.js
> Error:   43:2  error  Unnecessary semicolon  no-extra-semi
> 
> ✖ 1 problem (1 error, 0 warnings)
>   1 error and 0 warnings potentially fixable with the `--fix` option.
> ```

Oops, fixed it, rebased on main and pushed again!

2021-06-14 18:44 UTC, rwjblue approved these changes

2021-06-14 18:44 UTC, merged